const projectsArr = [{
    tittle: 'Pig E_Bank',
    rank: 1,
    URL: 'https://ajrsabet.github.io/Screen_Time_Tracker/',
    imageLoc: 'assets/images/Pig_E_Bank.png',
    discrption: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit architecto, ab incidunt fugit, eos maxime ea pariatur vel inventore distinctio recusandae vero cum sequi earum in? Nesciunt reprehenderit qui sed.',
    },
    {
    tittle: 'Javascript Quiz',
    rank: 2,
        URL: 'https://ajrsabet.github.io/Javascript_Quiz/',
    imageLoc: 'assets/images/Javascript_Quiz.png',
    discrption: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit architecto, ab incidunt fugit, eos maxime ea pariatur vel inventore distinctio recusandae vero cum sequi earum in? Nesciunt reprehenderit qui sed.',
    },
    {
    tittle: 'Password Generator',
    rank: 5,
        URL: 'https://ajrsabet.github.io/Password_Generator/',
    imageLoc: 'assets/images/Password_Generator.png',
    discrption: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit architecto, ab incidunt fugit, eos maxime ea pariatur vel inventore distinctio recusandae vero cum sequi earum in? Nesciunt reprehenderit qui sed.',
    },
    {
    tittle: 'Day Planner',
    rank: 4,
        URL: 'https://ajrsabet.github.io/Day_Planner/',
    imageLoc: 'assets/images/Day_Planner.png',
    discrption: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit architecto, ab incidunt fugit, eos maxime ea pariatur vel inventore distinctio recusandae vero cum sequi earum in? Nesciunt reprehenderit qui sed.',
    },
    {
    tittle: 'Weather Dashboard',
    rank: 3,
        URL: 'https://ajrsabet.github.io/Weather_Dashboard/',
    imageLoc: 'assets/images/Weather_Dashboard.png',
    discrption: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit architecto, ab incidunt fugit, eos maxime ea pariatur vel inventore distinctio recusandae vero cum sequi earum in? Nesciunt reprehenderit qui sed.',
    },
]